### ISSUE TITLE
Hmm ga bisa upload png jadi gw kirim di sini

### ISSUE THREAD

**Issue by hardianto01** [Not-found-squad/knights-canvas#4]
![IMG-20210601-WA0142](https://user-images.githubusercontent.com/71861395/120352790-b9082800-c333-11eb-9677-5741e6fc653f.jpg)
![IMG-20210601-WA0141](https://user-images.githubusercontent.com/71861395/120352793-ba395500-c333-11eb-91c3-ad7081cba79e.jpg)

Buat demote and promote

**Comment by Len-cmd** [comment]
Njir :v

**Comment by squad-404** [comment]
> ![IMG-20210601-WA0142](https://user-images.githubusercontent.com/71861395/120352790-b9082800-c333-11eb-9677-5741e6fc653f.jpg)
> ![IMG-20210601-WA0141](https://user-images.githubusercontent.com/71861395/120352793-ba395500-c333-11eb-91c3-ad7081cba79e.jpg)
> 
> Buat demote and promote

Kan bisa di cdn atau di up ke imgbb

**Comment by hardianto01** [comment]
Awomswok males soal nya

**Comment by hardianto01** [comment]
Btw itu dah bener blom

**Comment by squad-404** [comment]
> Btw itu dah bener blom

Lu kirim ke situ malah jadi jpg njir

Nih dah gw bersihin
Untuk demote

 this.assent = "https://i.ibb.co/3rRxkGg/1622592933341.png";

Untuk promote 

this.assent = "https://i.ibb.co/B45BXZP/1622592951945.png";

**Comment by hardianto01** [comment]
Demote udah tinggal promote nya index.js nya

**Comment by hardianto01** [comment]
Ok
