### ISSUE TITLE
Goobye2 gak bisa

### ISSUE THREAD

**Issue by NevtBotz** [Not-found-squad/knights-canvas#5]
TypeError: (intermediate value).setAvatar(...).setUsername(...).setBg(...).setGroupname is not a function
  
setGroupname not found

**Comment by squad-404** [comment]
> TypeError: (intermediate value).setAvatar(...).setUsername(...).setBg(...).setGroupname is not a function
> 
> setGroupname not found

ga pake `setGroupname` klo goodbye2, aneh aja soalnya klo _goodbye to/from "nama grup"_

![see](https://i.ibb.co/vsn64zZ/Goodbye.png)
